backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "journal"
    label: "ðŸ“– My Journal"
    folder: "src/stories"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
      - {label: "TÃ­tulo de la SesiÃ³n", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Cuerpo del Log", name: "body", widget: "markdown"}
      - {label: "Status_Mood", name: "status", widget: "select", options: ["Inspired ðŸŽ€", "Debugging ðŸ’»", "Dreaming âœ¨"]}