# Dentro de tu config.yml en collections:
    editor:
      preview: false # Para que se sienta m치s como escribir c칩digo puro
    fields:
      - {label: "ID de Sesi칩n", name: "title", widget: "string", hint: "Ej: LOG_002: Noche de c칩digo"}
      - {label: "Timestamp", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Contenido del Portal", name: "body", widget: "markdown"}
      - {label: "Mood_Status", name: "status", widget: "select", options: ["Inspired", "Debugging", "Evolving", "Soft_Mode"]}